"""
Prepare assets for the Eye Health dashboard + report.
  1. Exports the cleaned dataset to data.js (global var, works over file://).
  2. Renders 3 static exploratory PNG charts (correlation / distribution / trend).
  3. Prints the exact statistics cited in the report so nothing is hand-typed.
Run from this folder:  python prepare_data.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from scipy import stats

SRC = Path(r"C:\Downloads\eye_score_cleaned.xlsx")
HERE = Path(__file__).resolve().parent
ASSETS = HERE / "report_assets"
ASSETS.mkdir(exist_ok=True)

# Unified palette shared with the dashboard
INK = "#0f2a30"
TEAL = "#0d9488"
TEAL_DARK = "#115e59"
CORAL = "#ef6f53"
AMBER = "#f4a259"
GRID = "#d8e3e3"
PAPER = "#ffffff"

plt.rcParams.update({
    "figure.dpi": 130,
    "savefig.dpi": 130,
    "font.family": "DejaVu Sans",
    "font.size": 11,
    "axes.edgecolor": "#9fb4b4",
    "axes.linewidth": 0.9,
    "axes.titlesize": 13,
    "axes.titleweight": "bold",
    "axes.titlecolor": INK,
    "axes.labelcolor": INK,
    "text.color": INK,
    "xtick.color": "#4a6168",
    "ytick.color": "#4a6168",
    "axes.grid": True,
    "grid.color": GRID,
    "grid.linewidth": 0.8,
    "figure.facecolor": PAPER,
    "axes.facecolor": PAPER,
})

df = pd.read_excel(SRC, "Cleaned Data")

# ---------------------------------------------------------------- data.js
# arrays-of-columns keeps the payload small; floats rounded to 2 dp
export_cols = [c for c in df.columns if c != "id"]
payload = {
    "columns": ["id"] + export_cols,
    "id": df["id"].astype(int).tolist(),
}
for c in export_cols:
    if df[c].dtype.kind == "f":
        payload[c] = [round(float(v), 2) for v in df[c]]
    else:
        payload[c] = [int(v) for v in df[c]]

data_js = "// auto-generated by prepare_data.py — do not edit by hand\n"
data_js += "window.EYE_DATA = " + json.dumps(payload, separators=(",", ":")) + ";\n"
(HERE / "data.js").write_text(data_js, encoding="utf-8")
print(f"data.js written: {len(data_js)/1024:.0f} KB, {len(df)} rows")

# ---------------------------------------------------------------- helpers
def finish(ax_or_fig, path):
    plt.tight_layout()
    plt.savefig(ASSETS / path, bbox_inches="tight", facecolor=PAPER)
    plt.close()
    print("chart ->", path)

# ============================================================ 1. CORRELATION
# screen_time_hours vs eye_health_score, with regression line
x = df["screen_time_hours"].values
y = df["eye_health_score"].values
slope, intercept, r, p, se = stats.linregress(x, y)
fig, ax = plt.subplots(figsize=(7.4, 4.8))
ax.scatter(x, y, s=8, c=TEAL, alpha=0.18, edgecolors="none", rasterized=True)
xs = np.linspace(x.min(), x.max(), 100)
ax.plot(xs, intercept + slope * xs, color=CORAL, lw=2.6,
        label=f"OLS fit  (r = {r:.2f},  p < 0.001)")
ax.set_title("Correlation — More daily screen time, lower eye-health score")
ax.set_xlabel("Daily screen time (hours)")
ax.set_ylabel("Eye-health score (0–100)")
ax.legend(loc="upper right", frameon=True, facecolor="white", edgecolor=GRID)
finish(fig, "chart_correlation.png")
corr_r = r

# ============================================================ 2. DISTRIBUTION
v = df["eye_health_score"].values
fig, ax = plt.subplots(figsize=(7.4, 4.8))
n, bins, patches = ax.hist(v, bins=40, color=TEAL, alpha=0.85, edgecolor="white", linewidth=0.6)
mean_v, med_v = v.mean(), np.median(v)
ax.axvline(mean_v, color=CORAL, lw=2.2, label=f"Mean = {mean_v:.1f}")
ax.axvline(med_v, color=INK, lw=1.8, ls="--", label=f"Median = {med_v:.1f}")
ax.set_title("Distribution — Eye-health scores cluster near a healthy mid-60s")
ax.set_xlabel("Eye-health score (0–100)")
ax.set_ylabel("Number of respondents")
ax.legend(loc="upper right", frameon=True, facecolor="white", edgecolor=GRID)
finish(fig, "chart_distribution.png")

# ============================================================ 3. TREND (over age as life-course timeline)
g = df.groupby("age")["eye_health_score"].agg(["mean", "count"]).reset_index()
g = g[g["count"] >= 20]  # stable means only
fig, ax = plt.subplots(figsize=(7.4, 4.8))
ax.plot(g["age"], g["mean"], color=TEAL_DARK, lw=2.6)
ax.fill_between(g["age"], g["mean"], g["mean"].min() - 2, color=TEAL, alpha=0.10)
# light trend annotation
slope_a, intercept_a, r_a, p_a, se_a = stats.linregress(df["age"], df["eye_health_score"])
ax.set_title("Trend — Eye-health score declines steadily across the age span")
ax.set_xlabel("Age (years) — used as a life-course timeline (no date field in data)")
ax.set_ylabel("Mean eye-health score")
ax.set_ylim(g["mean"].min() - 2, g["mean"].max() + 2)
ax.text(0.02, 0.06, f"slope ≈ {slope_a:.2f} pts/yr   r = {r_a:.2f}",
        transform=ax.transAxes, color="#4a6168")
finish(fig, "chart_trend.png")

# ============================================================ stats for report
print("\n===== REPORT STATS =====")
print(f"rows={len(df)}  cols={df.shape[1]}")
print(f"eye_health mean={v.mean():.1f} median={np.median(v):.1f} sd={v.std():.1f} min={v.min():.1f} max={v.max():.1f}")
corr = df.drop(columns=['id']).corr()["eye_health_score"].drop("eye_health_score").sort_values()
print("corr with eye_health_score:")
for k, val in corr.items():
    print(f"  {k:>32}: {val:+.3f}")
print(f"screen_time vs eye_health r = {corr_r:.3f}")
print("glasses counts:", df['glasses_number'].value_counts().sort_index().to_dict())
by_g = df.groupby('glasses_number')['eye_health_score'].mean().round(1).to_dict()
print("mean eye_health by glasses:", by_g)
young = df[df.age<=20]['eye_health_score'].mean(); old = df[df.age>=70]['eye_health_score'].mean()
print(f"mean eye_health age<=20: {young:.1f}   age>=70: {old:.1f}")
print("age range", df.age.min(), df.age.max())
